[book]
title = "Makepad Documentation"
authors = ["Rik Arends", "Sebastian Michailidis", "Edward Tan"]
language = "en"
multilingual = false
src = "src"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "rust"
git-repository-url = "https://github.com/guofoo/makepad-book"
git-repository-icon = "fa-github"
